### ISSUE TITLE
Planned features

### ISSUE THREAD

**Issue by SebastianStehle** [LSViana/ydotnet#35] opened 2023-09-29 17:56 UTC
Nice project.

What is your planned scope? Are you also planning to publish ready to use packages for signalr or something that can easily be integrated into the server? Do you need help?

 I am planning to integrate it into https://github.com/squidex/squidex

**Comment by LSViana** [comment] 2023-09-30 16:19
Hi, @SebastianStehle!

Thanks for your interest in the project, it's nice to see that! First, I'd like to highlight that I'm working on this as a secondary project so the rhythm of development & maintenance is currently slower than I'd like it to be.

> What is your planned scope?

The long-term plans for the project are to support all features exposed by [Yrs](https://github.com/y-crdt/y-crdt) and make them available on C#. Currently, only the "core" of the library has been developed.

I'm currently working on:
- Adding unit tests to prevent regressions;
- Adding sample use cases to ensure there are no memory leaks.

The roadmap for this project is available in the [YDotNet Implementation board](https://github.com/users/LSViana/projects/1). If you're interested in something specific that's not been added there, please let me know.

---

> Are you also planning to publish ready to use packages for signalr or something that can easily be integrated into the server?

Yes, definitely! I intend to publish NuGet packages to allow C# code to connect with other Yjs clients through networks. I can't tell you exactly right now but I believe the first network provider will be for WebSockets (so that web apps can use the [y-websocket](https://github.com/yjs/y-websocket), for example). Would this fit for your use case?

---

> Do you need help?

Yes! Right now, it'd be nice to get some help for either one of these tasks:

- [Plan the implementation of the network layer
](https://github.com/users/LSViana/projects/1?pane=issue&itemId=35371897)
- [Build Rust binaries automatically](https://github.com/users/LSViana/projects/1?pane=issue&itemId=36466960)

If you're available to contribute, feel free to make a fork and submit a PR.

**Comment by SebastianStehle** [comment] 2023-09-30 17:26
> Yes, definitely! I intend to publish NuGet packages to allow C# code to connect with other Yjs clients through networks. I can't tell you exactly right now but I believe the first network provider will be for WebSockets (so that web apps can use the [y-websocket](https://github.com/yjs/y-websocket), for example). Would this fit for your use case?

Yes, I am not biased here. But then you have to solve a few topics, that are already handled by signalr, such as scaling and a backplane. Should not be too complicated.

**Comment by SebastianStehle** [comment] 2023-10-01 09:43
Would you explain me the motivation of this project versus ycs and why are you not creating a wrapper over yrs (https://github.com/y-crdt/y-crdt). Seems to have the best performance at the moment.

**Comment by LSViana** [comment] 2023-10-01 14:02
Hi, @SebastianStehle!

Let me answer your questions in parts to explain each part clearly:

> (...) why are you not creating a wrapper over [yrs](https://github.com/y-crdt/y-crdt) (...)

This project is a wrapper over Yrs. It exposes C# bindings that calls into Rust code.

> Would you explain me the motivation of this project versus ycs (...)

The [Ycs project](https://github.com/yjs/ycs/) original author no longer maintains it and the codebase is too large to be kept up-to-date.

Besides that, since there's a central Rust implementation now, it doesn't make sense to keep Ycs anymore because the effort to maintain two codebases with the same features over time would be too big.

> Yes, I am not biased here. But then you have to solve a few topics, that are already handled by signalr, such as scaling and a backplane. Should not be too complicated.

Sure, this will all be taken into consideration when the time comes. I'll add it to the list of future plans for the project.

---

Does this answer your questions? If you'd like to know anything else, please let me know.

**Comment by LSViana** [comment] 2023-10-02 23:08
@SebastianStehle If there's nothing else to add here, feel free to close this thread or I'll close it myself within a couple of days.

**Closed** 2023-10-03 05:40 UTC
